# Dependencies
markdown:       kramdown
highlighter: 	rouge
gems: 		[jekyll-paginate, jekyll-sitemap]



# Permalinks
permalink:        pretty

# Setup
title:            Veronika Rot
tagline:          'Samostojna kulturna delavka, prevajalka iz španščine in katalonščine'
description:      'zgodbe.eu'
url:              http://brontosaurusrex.github.io/zgodbe/

author:
  name:           'Veronika'
#  url:            http://zgodbe.eu

paginate:         7

# Custom vars




